/* ============================================================================
 * Adaptive Hypertrophy Coach — Exercise Database v2 (DRAFT for review)
 * ----------------------------------------------------------------------------
 * Superset of the original ~55-exercise DB. Every legacy name is preserved
 * verbatim so existing exerciseProgress / logs / look-back keep mapping.
 *
 * Enriched schema, per exercise:
 *   name            (string)  canonical, unique — this is the primary key
 *   equipment       (enum)    barbell | dumbbell | cable | machine | bodyweight
 *   movementPattern (enum)    see PATTERNS below
 *   primaryMuscle   (enum)    see MUSCLES below
 *   secondaryMuscles(string[])subset of MUSCLES
 *   unilateral      (bool)    trained one limb at a time
 *   focus           (string)  1-2 sentence form cue
 *   alternative     (string)  canonical name of a same-pattern swap (must exist)
 *
 * Controlled vocab (enforced by validate-exercise-db.js):
 *   PATTERNS = horizontalPush, inclinePush, declinePush, verticalPush,
 *              horizontalPull, verticalPull, squat, hipHinge, lunge,
 *              chestFly, lateralRaise, frontRaise, rearDelt, shrug,
 *              latIsolation, bicepCurl, tricepExtension, quadIsolation,
 *              hamstringCurl, calfRaise
 *   MUSCLES  = chest, lats, upper-back, rear-delts, front-delts, side-delts,
 *              biceps, triceps, forearms, quads, hamstrings, glutes, calves
 *   EQUIPMENT= barbell, dumbbell, cable, machine, bodyweight
 * ========================================================================== */

const ExerciseDatabase = {
  chest: {
    compound: [
      { name: 'Flat Barbell Bench Press', equipment: 'barbell', movementPattern: 'horizontalPush', primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'front-delts'], unilateral: false, focus: 'Maintain a stable base, control the descent, and drive explosively. Keep elbows slightly tucked at 45 degrees.', alternative: 'Flat Dumbbell Press' },
      { name: 'Incline Barbell Press', equipment: 'barbell', movementPattern: 'inclinePush', primaryMuscle: 'chest', secondaryMuscles: ['front-delts', 'triceps'], unilateral: false, focus: 'Set bench to 30-45 degrees. Focus on upper chest engagement. Control the eccentric phase.', alternative: 'Incline Dumbbell Press' },
      { name: 'Flat Dumbbell Press', equipment: 'dumbbell', movementPattern: 'horizontalPush', primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'front-delts'], unilateral: false, focus: 'Allow a deeper stretch at the bottom. Press dumbbells together at the top for peak contraction.', alternative: 'Flat Barbell Bench Press' },
      { name: 'Incline Dumbbell Press', equipment: 'dumbbell', movementPattern: 'inclinePush', primaryMuscle: 'chest', secondaryMuscles: ['front-delts', 'triceps'], unilateral: false, focus: 'Focus on squeezing your upper chest at the top. Control the weight throughout.', alternative: 'Incline Barbell Press' },
      { name: 'Decline Push-ups', equipment: 'bodyweight', movementPattern: 'horizontalPush', primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'front-delts'], unilateral: false, focus: 'Elevate your feet to increase difficulty. Focus on engaging your lower chest.', alternative: 'Machine Chest Press' },
      { name: 'Machine Chest Press', equipment: 'machine', movementPattern: 'horizontalPush', primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'front-delts'], unilateral: false, focus: 'Great for isolating chest without stabilizer fatigue. Focus on mind-muscle connection.', alternative: 'Flat Dumbbell Press' },
      { name: 'Decline Barbell Bench Press', equipment: 'barbell', movementPattern: 'declinePush', primaryMuscle: 'chest', secondaryMuscles: ['triceps'], unilateral: false, focus: 'Targets lower chest fibers. Keep a controlled descent to the lower sternum.', alternative: 'Machine Decline Press' },
      { name: 'Decline Dumbbell Press', equipment: 'dumbbell', movementPattern: 'declinePush', primaryMuscle: 'chest', secondaryMuscles: ['triceps'], unilateral: false, focus: 'Lower chest emphasis with a longer range of motion than the barbell version.', alternative: 'Decline Barbell Bench Press' },
      { name: 'Smith Machine Bench Press', equipment: 'machine', movementPattern: 'horizontalPush', primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'front-delts'], unilateral: false, focus: 'Fixed bar path lets you push closer to failure safely. Keep wrists stacked over elbows.', alternative: 'Flat Barbell Bench Press' },
      { name: 'Smith Machine Incline Press', equipment: 'machine', movementPattern: 'inclinePush', primaryMuscle: 'chest', secondaryMuscles: ['front-delts', 'triceps'], unilateral: false, focus: 'Stable path for upper-chest overload. Set bench to roughly 30 degrees.', alternative: 'Incline Barbell Press' },
      { name: 'Machine Incline Press', equipment: 'machine', movementPattern: 'inclinePush', primaryMuscle: 'chest', secondaryMuscles: ['front-delts', 'triceps'], unilateral: false, focus: 'Upper-chest focus with no balance demand. Drive through the handles and squeeze.', alternative: 'Incline Dumbbell Press' },
      { name: 'Machine Decline Press', equipment: 'machine', movementPattern: 'declinePush', primaryMuscle: 'chest', secondaryMuscles: ['triceps'], unilateral: false, focus: 'Lower-chest press without setup hassle. Keep tension off the lockout.', alternative: 'Decline Barbell Bench Press' },
      { name: 'Weighted Dips (Chest)', equipment: 'bodyweight', movementPattern: 'declinePush', primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'front-delts'], unilateral: false, focus: 'Lean the torso forward and flare slightly to bias the chest. Add weight via belt.', alternative: 'Decline Dumbbell Press' },
      { name: 'Floor Press (Barbell)', equipment: 'barbell', movementPattern: 'horizontalPush', primaryMuscle: 'chest', secondaryMuscles: ['triceps'], unilateral: false, focus: 'Limited ROM reduces shoulder strain and overloads the mid-press. Pause on the floor.', alternative: 'Flat Dumbbell Press' },
      { name: 'Standard Push-ups', equipment: 'bodyweight', movementPattern: 'horizontalPush', primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'front-delts'], unilateral: false, focus: 'Keep a rigid plank and full ROM. Add a backpack or band for progression.', alternative: 'Decline Push-ups' },
      { name: 'Guillotine Press', equipment: 'barbell', movementPattern: 'inclinePush', primaryMuscle: 'chest', secondaryMuscles: ['front-delts'], unilateral: false, focus: 'Lower the bar toward the upper chest/clavicle with flared elbows for upper-chest stretch. Use light load.', alternative: 'Incline Barbell Press' }
    ],
    isolation: [
      { name: 'Incline Dumbbell Flyes', equipment: 'dumbbell', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: ['front-delts'], unilateral: false, focus: 'Maintain a slight bend in your elbows throughout. Feel the stretch at the bottom.', alternative: 'Cable Flyes (Low to High)' },
      { name: 'Cable Flyes (High to Low)', equipment: 'cable', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: [], unilateral: false, focus: 'Bring cables down and across your body, squeezing chest at peak contraction.', alternative: 'Pec Deck Machine' },
      { name: 'Cable Flyes (Low to High)', equipment: 'cable', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: ['front-delts'], unilateral: false, focus: 'Target upper chest fibers. Bring cables up and together in front of your face.', alternative: 'Incline Dumbbell Flyes' },
      { name: 'Pec Deck Machine', equipment: 'machine', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: [], unilateral: false, focus: 'Focus on squeezing your chest together at the peak. Control the negative.', alternative: 'Cable Crossovers' },
      { name: 'Flat Dumbbell Flyes', equipment: 'dumbbell', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: [], unilateral: false, focus: 'Open the arms in a wide arc with soft elbows. Stop before the dumbbells touch to keep tension.', alternative: 'Pec Deck Machine' },
      { name: 'Cable Crossovers', equipment: 'cable', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: [], unilateral: false, focus: 'Constant tension across the full arc. Cross the wrists slightly at the midline.', alternative: 'Pec Deck Machine' },
      { name: 'Low-to-High Dumbbell Flyes', equipment: 'dumbbell', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: ['front-delts'], unilateral: false, focus: 'Sweep the dumbbells up and in to bias the upper chest. Keep a fixed elbow angle.', alternative: 'Cable Flyes (Low to High)' },
      { name: 'Machine Chest Flye', equipment: 'machine', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: [], unilateral: false, focus: 'Pin the back to the pad and drive the pads together. Pause on the squeeze.', alternative: 'Pec Deck Machine' },
      { name: 'Banded Chest Flye', equipment: 'cable', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: [], unilateral: false, focus: 'Resistance peaks at the contraction. Great low-fatigue finisher for the chest.', alternative: 'Cable Crossovers' },
      { name: 'Svend Press', equipment: 'dumbbell', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: [], unilateral: false, focus: 'Press two plates together and push out; the inward squeeze targets the inner chest.', alternative: 'Pec Deck Machine' },
      { name: 'Incline Cable Flye', equipment: 'cable', movementPattern: 'chestFly', primaryMuscle: 'chest', secondaryMuscles: ['front-delts'], unilateral: false, focus: 'On an incline bench between cables, hug upward for an upper-chest stretch with constant tension.', alternative: 'Incline Dumbbell Flyes' }
    ]
  },
  back: {
    compound: [
      { name: 'Barbell Rows', equipment: 'barbell', movementPattern: 'horizontalPull', primaryMuscle: 'lats', secondaryMuscles: ['upper-back', 'biceps', 'rear-delts'], unilateral: false, focus: 'Pull towards your lower chest/upper abs. Squeeze shoulder blades together at the top.', alternative: 'T-Bar Rows' },
      { name: 'T-Bar Rows', equipment: 'barbell', movementPattern: 'horizontalPull', primaryMuscle: 'upper-back', secondaryMuscles: ['lats', 'biceps'], unilateral: false, focus: 'Keep your core engaged and back flat. Focus on pulling with your back muscles.', alternative: 'Barbell Rows' },
      { name: 'Pull-ups', equipment: 'bodyweight', movementPattern: 'verticalPull', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], unilateral: false, focus: 'Use a full range of motion from dead hang. Focus on engaging your lats.', alternative: 'Wide-Grip Lat Pulldowns' },
      { name: 'Wide-Grip Lat Pulldowns', equipment: 'cable', movementPattern: 'verticalPull', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], unilateral: false, focus: 'Pull the bar to your upper chest, squeezing your lats at the bottom.', alternative: 'Pull-ups' },
      { name: 'Close-Grip Lat Pulldowns', equipment: 'cable', movementPattern: 'verticalPull', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], unilateral: false, focus: 'Use a V-bar or close grip. Emphasizes lower lats and thickness.', alternative: 'Neutral-Grip Lat Pulldowns' },
      { name: 'Neutral-Grip Lat Pulldowns', equipment: 'cable', movementPattern: 'verticalPull', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], unilateral: false, focus: 'Palms facing each other. Pull to upper chest for optimal lat engagement.', alternative: 'Wide-Grip Lat Pulldowns' },
      { name: 'Seated Cable Rows', equipment: 'cable', movementPattern: 'horizontalPull', primaryMuscle: 'upper-back', secondaryMuscles: ['lats', 'biceps'], unilateral: false, focus: 'Pull handle towards midsection. Retract shoulder blades and squeeze.', alternative: 'Single-Arm Dumbbell Rows' },
      { name: 'Single-Arm Dumbbell Rows', equipment: 'dumbbell', movementPattern: 'horizontalPull', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], unilateral: true, focus: 'Support yourself on a bench. Pull the dumbbell to your hip, squeezing your lat.', alternative: 'Seated Cable Rows' },
      { name: 'Chest-Supported Dumbbell Rows', equipment: 'dumbbell', movementPattern: 'horizontalPull', primaryMuscle: 'upper-back', secondaryMuscles: ['lats', 'biceps'], unilateral: false, focus: 'Chest on an incline pad removes momentum. Row to the hips and squeeze the mid-back.', alternative: 'Seated Cable Rows' },
      { name: 'Chest-Supported T-Bar Row (Machine)', equipment: 'machine', movementPattern: 'horizontalPull', primaryMuscle: 'upper-back', secondaryMuscles: ['lats'], unilateral: false, focus: 'Braced against the pad for strict back loading. Drive elbows back, not up.', alternative: 'T-Bar Rows' },
      { name: 'Pendlay Rows', equipment: 'barbell', movementPattern: 'horizontalPull', primaryMuscle: 'upper-back', secondaryMuscles: ['lats', 'biceps'], unilateral: false, focus: 'Reset the bar on the floor each rep and pull explosively to the lower chest.', alternative: 'Barbell Rows' },
      { name: 'Chin-ups', equipment: 'bodyweight', movementPattern: 'verticalPull', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], unilateral: false, focus: 'Supinated grip adds biceps involvement. Pull the chest to the bar from a full hang.', alternative: 'Pull-ups' },
      { name: 'Weighted Pull-ups', equipment: 'bodyweight', movementPattern: 'verticalPull', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], unilateral: false, focus: 'Add load via belt once bodyweight reps are easy. Control the negative.', alternative: 'Pull-ups' },
      { name: 'Machine Row (Hammer Strength)', equipment: 'machine', movementPattern: 'horizontalPull', primaryMuscle: 'upper-back', secondaryMuscles: ['lats'], unilateral: false, focus: 'Independent arms allow a strong stretch and squeeze. Keep the chest pinned to the pad.', alternative: 'Seated Cable Rows' },
      { name: 'Inverted Rows', equipment: 'bodyweight', movementPattern: 'horizontalPull', primaryMuscle: 'upper-back', secondaryMuscles: ['lats', 'biceps'], unilateral: false, focus: 'Body in a straight line under a fixed bar. Raise feet to make it harder.', alternative: 'Chest-Supported Dumbbell Rows' },
      { name: 'Meadows Rows', equipment: 'barbell', movementPattern: 'horizontalPull', primaryMuscle: 'lats', secondaryMuscles: ['upper-back', 'biceps'], unilateral: true, focus: 'Stand perpendicular to a landmine and row one arm with a wide overhand grip.', alternative: 'Single-Arm Dumbbell Rows' },
      { name: 'Kroc Rows', equipment: 'dumbbell', movementPattern: 'horizontalPull', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], unilateral: true, focus: 'Heavy, slightly looser single-arm rows for high reps and grip. Drive the elbow to the hip.', alternative: 'Single-Arm Dumbbell Rows' },
      { name: 'Lat Pulldown (Underhand)', equipment: 'cable', movementPattern: 'verticalPull', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], unilateral: false, focus: 'Supinated grip biases the lower lats. Drive elbows down and into the sides.', alternative: 'Close-Grip Lat Pulldowns' },
      { name: 'Straight-Bar Cable Row', equipment: 'cable', movementPattern: 'horizontalPull', primaryMuscle: 'upper-back', secondaryMuscles: ['lats'], unilateral: false, focus: 'Row a straight bar to the sternum with a tall chest to hit the upper back.', alternative: 'Seated Cable Rows' }
    ],
    isolation: [
      { name: 'Reverse Flyes', equipment: 'dumbbell', movementPattern: 'rearDelt', primaryMuscle: 'rear-delts', secondaryMuscles: ['upper-back'], unilateral: false, focus: 'Slight bend in elbows. Focus on rear deltoids and upper back squeeze.', alternative: 'Face Pulls' },
      { name: 'Face Pulls', equipment: 'cable', movementPattern: 'rearDelt', primaryMuscle: 'rear-delts', secondaryMuscles: ['upper-back'], unilateral: false, focus: 'Pull rope towards your face/forehead. Focus on rear delts and external rotation.', alternative: 'Reverse Flyes' },
      { name: 'Straight-Arm Pulldowns', equipment: 'cable', movementPattern: 'latIsolation', primaryMuscle: 'lats', secondaryMuscles: [], unilateral: false, focus: 'Keep arms straight, pull bar down to thighs. Great lat isolation.', alternative: 'Dumbbell Pullovers' },
      { name: 'Dumbbell Pullovers', equipment: 'dumbbell', movementPattern: 'latIsolation', primaryMuscle: 'lats', secondaryMuscles: ['chest'], unilateral: false, focus: 'Lower one dumbbell behind the head for a big lat stretch, then pull it over the chest.', alternative: 'Straight-Arm Pulldowns' },
      { name: 'Cable Reverse Flyes', equipment: 'cable', movementPattern: 'rearDelt', primaryMuscle: 'rear-delts', secondaryMuscles: ['upper-back'], unilateral: false, focus: 'Cross-cable rear flye gives constant tension. Lead with the elbows, not the hands.', alternative: 'Reverse Flyes' },
      { name: 'Rear Delt Machine (Reverse Pec Deck)', equipment: 'machine', movementPattern: 'rearDelt', primaryMuscle: 'rear-delts', secondaryMuscles: ['upper-back'], unilateral: false, focus: 'Drive the handles back in a wide arc. Pause briefly at full contraction.', alternative: 'Face Pulls' },
      { name: 'Bent-Over Dumbbell Reverse Flyes', equipment: 'dumbbell', movementPattern: 'rearDelt', primaryMuscle: 'rear-delts', secondaryMuscles: ['upper-back'], unilateral: false, focus: 'Hinge forward and raise dumbbells out to the sides with soft elbows.', alternative: 'Reverse Flyes' },
      { name: 'Incline Prone Dumbbell Rear Delt Raise', equipment: 'dumbbell', movementPattern: 'rearDelt', primaryMuscle: 'rear-delts', secondaryMuscles: [], unilateral: false, focus: 'Chest on an incline bench removes momentum for strict rear-delt work.', alternative: 'Bent-Over Dumbbell Reverse Flyes' },
      { name: 'Cable Straight-Arm Pushdown', equipment: 'cable', movementPattern: 'latIsolation', primaryMuscle: 'lats', secondaryMuscles: [], unilateral: false, focus: 'Push a straight bar down with locked arms, hinging slightly to bias the lats.', alternative: 'Straight-Arm Pulldowns' },
      { name: 'Machine Pullover', equipment: 'machine', movementPattern: 'latIsolation', primaryMuscle: 'lats', secondaryMuscles: [], unilateral: false, focus: 'Drive the pad down with the elbows. Excellent isolated lat stretch and contraction.', alternative: 'Dumbbell Pullovers' },
      { name: 'Shrugs (Barbell)', equipment: 'barbell', movementPattern: 'shrug', primaryMuscle: 'upper-back', secondaryMuscles: [], unilateral: false, focus: 'Elevate the shoulders straight up and pause; avoid rolling. Targets the traps.', alternative: 'Dumbbell Shrugs' },
      { name: 'Dumbbell Shrugs', equipment: 'dumbbell', movementPattern: 'shrug', primaryMuscle: 'upper-back', secondaryMuscles: [], unilateral: false, focus: 'Heavy shrugs with a full elevation and pause. Keep the neck relaxed.', alternative: 'Shrugs (Barbell)' }
    ]
  },
  shoulders: {
    compound: [
      { name: 'Overhead Press (Barbell)', equipment: 'barbell', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], unilateral: false, focus: 'Engage core and glutes for stability. Press straight overhead with full extension.', alternative: 'Seated Dumbbell Shoulder Press' },
      { name: 'Seated Dumbbell Shoulder Press', equipment: 'dumbbell', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], unilateral: false, focus: 'Press dumbbells overhead. Keep core tight and avoid excessive arching.', alternative: 'Overhead Press (Barbell)' },
      { name: 'Arnold Press', equipment: 'dumbbell', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], unilateral: false, focus: 'Rotate palms from facing you to facing forward during the press. Great for overall delt development.', alternative: 'Seated Dumbbell Shoulder Press' },
      { name: 'Standing Dumbbell Shoulder Press', equipment: 'dumbbell', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], unilateral: false, focus: 'Press overhead while bracing the core hard. No leg drive — keep it strict.', alternative: 'Seated Dumbbell Shoulder Press' },
      { name: 'Push Press', equipment: 'barbell', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], unilateral: false, focus: 'Use a small leg dip to drive heavier loads overhead. Control the eccentric.', alternative: 'Overhead Press (Barbell)' },
      { name: 'Machine Shoulder Press', equipment: 'machine', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], unilateral: false, focus: 'Fixed path lets you push near failure safely. Press to near lockout and control down.', alternative: 'Seated Dumbbell Shoulder Press' },
      { name: 'Smith Machine Overhead Press', equipment: 'machine', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], unilateral: false, focus: 'Guided bar path for stable overload. Sit or stand with the bar over the mid-foot.', alternative: 'Overhead Press (Barbell)' },
      { name: 'Seated Barbell Overhead Press', equipment: 'barbell', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], unilateral: false, focus: 'Seated against an upright bench removes leg drive for strict delt work.', alternative: 'Overhead Press (Barbell)' },
      { name: 'Z Press', equipment: 'barbell', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], unilateral: false, focus: 'Press from the floor with legs straight; demands huge core and strict delt drive.', alternative: 'Seated Barbell Overhead Press' },
      { name: 'Landmine Press', equipment: 'barbell', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], unilateral: true, focus: 'Press the landmine up and slightly forward; a shoulder-friendly pressing arc.', alternative: 'Standing Dumbbell Shoulder Press' },
      { name: 'Bradford Press', equipment: 'barbell', movementPattern: 'verticalPush', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts'], unilateral: false, focus: 'Press just over the head and lower behind, alternating front and back for constant delt tension.', alternative: 'Overhead Press (Barbell)' }
    ],
    isolation: [
      { name: 'Seated Dumbbell Lateral Raises', equipment: 'dumbbell', movementPattern: 'lateralRaise', primaryMuscle: 'side-delts', secondaryMuscles: [], unilateral: false, focus: 'Raise to side with slight bend in elbows. Focus on medial deltoids.', alternative: 'Cable Lateral Raises' },
      { name: 'Cable Lateral Raises', equipment: 'cable', movementPattern: 'lateralRaise', primaryMuscle: 'side-delts', secondaryMuscles: [], unilateral: false, focus: 'Constant tension throughout. Great for time under tension.', alternative: 'Seated Dumbbell Lateral Raises' },
      { name: 'Front Raises', equipment: 'dumbbell', movementPattern: 'frontRaise', primaryMuscle: 'front-delts', secondaryMuscles: [], unilateral: false, focus: 'Raise weight to shoulder height. Focus on anterior deltoids.', alternative: 'Cable Front Raises' },
      { name: 'Standing Dumbbell Lateral Raises', equipment: 'dumbbell', movementPattern: 'lateralRaise', primaryMuscle: 'side-delts', secondaryMuscles: [], unilateral: false, focus: 'Lead with the elbows and raise to shoulder height. Avoid swinging or shrugging.', alternative: 'Cable Lateral Raises' },
      { name: 'Machine Lateral Raises', equipment: 'machine', movementPattern: 'lateralRaise', primaryMuscle: 'side-delts', secondaryMuscles: [], unilateral: false, focus: 'Pads against the outer arms give smooth resistance. Drive up and pause at the top.', alternative: 'Cable Lateral Raises' },
      { name: 'Leaning Cable Lateral Raise', equipment: 'cable', movementPattern: 'lateralRaise', primaryMuscle: 'side-delts', secondaryMuscles: [], unilateral: true, focus: 'Lean away from the stack to load the side delt through a longer range.', alternative: 'Cable Lateral Raises' },
      { name: 'Cable Front Raises', equipment: 'cable', movementPattern: 'frontRaise', primaryMuscle: 'front-delts', secondaryMuscles: [], unilateral: false, focus: 'Raise the handle to eye level with constant tension. Keep the torso still.', alternative: 'Front Raises' },
      { name: 'Plate Front Raise', equipment: 'dumbbell', movementPattern: 'frontRaise', primaryMuscle: 'front-delts', secondaryMuscles: [], unilateral: false, focus: 'Hold a plate at the edges and raise to eye level under control.', alternative: 'Front Raises' },
      { name: 'Barbell Front Raise', equipment: 'barbell', movementPattern: 'frontRaise', primaryMuscle: 'front-delts', secondaryMuscles: [], unilateral: false, focus: 'Raise a barbell to shoulder height with both hands. Avoid leaning back.', alternative: 'Cable Front Raises' },
      { name: 'Dumbbell Upright Rows', equipment: 'dumbbell', movementPattern: 'lateralRaise', primaryMuscle: 'side-delts', secondaryMuscles: ['upper-back'], unilateral: false, focus: 'Pull dumbbells up the body leading with the elbows to a comfortable height.', alternative: 'Cable Upright Rows' },
      { name: 'Cable Upright Rows', equipment: 'cable', movementPattern: 'lateralRaise', primaryMuscle: 'side-delts', secondaryMuscles: ['upper-back'], unilateral: false, focus: 'Smooth upright pull with constant tension. Stop at chest height to spare the shoulders.', alternative: 'Dumbbell Upright Rows' },
      { name: 'Barbell Upright Rows', equipment: 'barbell', movementPattern: 'lateralRaise', primaryMuscle: 'side-delts', secondaryMuscles: ['upper-back'], unilateral: false, focus: 'Use a shoulder-width grip and lead with the elbows. Avoid going too high.', alternative: 'Cable Upright Rows' },
      { name: 'Cable Y-Raise', equipment: 'cable', movementPattern: 'frontRaise', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts'], unilateral: false, focus: 'Raise the handles up and out into a Y to hit the front and side delts together.', alternative: 'Cable Front Raises' },
      { name: 'Lu Raises', equipment: 'dumbbell', movementPattern: 'lateralRaise', primaryMuscle: 'side-delts', secondaryMuscles: ['front-delts'], unilateral: false, focus: 'Raise dumbbells all the way overhead in a wide arc for a long side-delt ROM. Use light load.', alternative: 'Standing Dumbbell Lateral Raises' },
      { name: 'Partial Lateral Raises (21s)', equipment: 'dumbbell', movementPattern: 'lateralRaise', primaryMuscle: 'side-delts', secondaryMuscles: [], unilateral: false, focus: 'Bottom-half partials, top-half partials, then full reps to torch the side delts.', alternative: 'Standing Dumbbell Lateral Raises' }
    ]
  },
  biceps: {
    exercises: [
      { name: 'Barbell Curls', equipment: 'barbell', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], unilateral: false, focus: 'Keep elbows pinned to sides. Control both concentric and eccentric phases.', alternative: 'EZ-Bar Curls' },
      { name: 'Dumbbell Bicep Curls', equipment: 'dumbbell', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], unilateral: false, focus: 'Alternate or simultaneous. Avoid swinging. Full range of motion.', alternative: 'Hammer Curls' },
      { name: 'Hammer Curls', equipment: 'dumbbell', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], unilateral: false, focus: 'Neutral grip targets biceps and brachialis. Keep elbows stationary.', alternative: 'Rope Hammer Curls' },
      { name: 'Incline Dumbbell Curls', equipment: 'dumbbell', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: [], unilateral: false, focus: 'Set bench to 45-60 degrees. Great stretch on long head of biceps.', alternative: 'Concentration Curls' },
      { name: 'Preacher Curls', equipment: 'barbell', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: [], unilateral: false, focus: 'Isolates biceps by eliminating momentum. Focus on the squeeze at top.', alternative: 'Machine Preacher Curls' },
      { name: 'Cable Curls', equipment: 'cable', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: [], unilateral: false, focus: 'Constant tension. Great for finishing sets or drop sets.', alternative: 'Dumbbell Bicep Curls' },
      { name: 'EZ-Bar Curls', equipment: 'barbell', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], unilateral: false, focus: 'Angled grip eases wrist strain. Keep elbows fixed and curl under control.', alternative: 'Barbell Curls' },
      { name: 'Rope Hammer Curls', equipment: 'cable', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], unilateral: false, focus: 'Neutral rope grip with constant tension for the brachialis and outer arm.', alternative: 'Hammer Curls' },
      { name: 'Concentration Curls', equipment: 'dumbbell', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: [], unilateral: true, focus: 'Brace the elbow on the inner thigh and curl with a hard peak squeeze.', alternative: 'Incline Dumbbell Curls' },
      { name: 'Machine Preacher Curls', equipment: 'machine', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: [], unilateral: false, focus: 'Strict preacher pattern with smooth resistance. Pause on the squeeze, control the stretch.', alternative: 'Preacher Curls' },
      { name: 'Spider Curls', equipment: 'dumbbell', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: [], unilateral: false, focus: 'Chest on an incline bench, arms hanging straight down for a strict peak contraction.', alternative: 'Incline Dumbbell Curls' },
      { name: 'Cable Rope Curls', equipment: 'cable', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], unilateral: false, focus: 'Curl and twist the rope out at the top for an extra biceps squeeze.', alternative: 'Cable Curls' },
      { name: 'Bayesian Cable Curls', equipment: 'cable', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: [], unilateral: true, focus: 'Face away from the stack with the arm behind the body for a deep stretch under tension.', alternative: 'Cable Curls' },
      { name: 'EZ-Bar Preacher Curls', equipment: 'barbell', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: [], unilateral: false, focus: 'Preacher bench with an EZ-bar for wrist comfort. Control the bottom stretch.', alternative: 'Preacher Curls' },
      { name: 'Zottman Curls', equipment: 'dumbbell', movementPattern: 'bicepCurl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], unilateral: false, focus: 'Curl up supinated, rotate to pronated, and lower slowly for biceps and forearm work.', alternative: 'Hammer Curls' },
      { name: 'Reverse Barbell Curls', equipment: 'barbell', movementPattern: 'bicepCurl', primaryMuscle: 'forearms', secondaryMuscles: ['biceps'], unilateral: false, focus: 'Pronated grip emphasizes the brachioradialis and forearm extensors. Use lighter load.', alternative: 'EZ-Bar Curls' }
    ]
  },
  triceps: {
    exercises: [
      { name: 'Close-Grip Bench Press', equipment: 'barbell', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: ['chest'], unilateral: false, focus: 'Grip just inside shoulder width. Keep elbows tucked. Great compound movement.', alternative: 'Diamond Push-ups' },
      { name: 'Tricep Pushdowns', equipment: 'cable', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: false, focus: 'Keep elbows pinned to sides. Fully extend arms and squeeze triceps.', alternative: 'Overhead Dumbbell Extension' },
      { name: 'Overhead Dumbbell Extension', equipment: 'dumbbell', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: false, focus: 'Lower weight behind head, stretch triceps. Press up and squeeze.', alternative: 'Cable Overhead Extension' },
      { name: 'Dumbbell Skullcrushers', equipment: 'dumbbell', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: false, focus: 'Lower towards forehead, keeping elbows pointed up. Focus on triceps extension.', alternative: 'EZ-Bar Skullcrushers' },
      { name: 'Rope Pushdowns', equipment: 'cable', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: false, focus: 'Split the rope at the bottom for extra contraction. Keep elbows stationary.', alternative: 'V-Bar Pushdowns' },
      { name: 'Tricep Dips', equipment: 'bodyweight', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: ['chest', 'front-delts'], unilateral: false, focus: 'Lean slightly forward. Control the descent and push through triceps.', alternative: 'Bench Dips' },
      { name: 'Diamond Push-ups', equipment: 'bodyweight', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: ['chest'], unilateral: false, focus: 'Hands form a diamond under the chest. Keep elbows close and lower fully.', alternative: 'Tricep Dips' },
      { name: 'Cable Overhead Extension', equipment: 'cable', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: false, focus: 'Face away from the stack and extend overhead for a stretched, constant-tension triceps hit.', alternative: 'Overhead Dumbbell Extension' },
      { name: 'EZ-Bar Skullcrushers', equipment: 'barbell', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: false, focus: 'Lower the EZ-bar to the forehead or behind the head with elbows fixed.', alternative: 'Dumbbell Skullcrushers' },
      { name: 'V-Bar Pushdowns', equipment: 'cable', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: false, focus: 'Pronated V-bar grip for a strong lockout. Pin the elbows and fully extend.', alternative: 'Rope Pushdowns' },
      { name: 'Bench Dips', equipment: 'bodyweight', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: false, focus: 'Hands on a bench behind you, lower the hips and press up. Elevate feet to progress.', alternative: 'Tricep Dips' },
      { name: 'Close-Grip Push-ups', equipment: 'bodyweight', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: ['chest'], unilateral: false, focus: 'Narrow hand placement with elbows tucked tight to the ribs.', alternative: 'Diamond Push-ups' },
      { name: 'Single-Arm Cable Pushdown', equipment: 'cable', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: true, focus: 'One arm with a supinated handle for a strong peak contraction and even development.', alternative: 'Tricep Pushdowns' },
      { name: 'Machine Tricep Extension', equipment: 'machine', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: false, focus: 'Fixed path lets you push to failure safely. Lock out and control the return.', alternative: 'Tricep Pushdowns' },
      { name: 'JM Press', equipment: 'barbell', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: ['chest'], unilateral: false, focus: 'A hybrid of close-grip press and skullcrusher; lower toward the chin with tucked elbows.', alternative: 'Close-Grip Bench Press' },
      { name: 'Cable Kickbacks', equipment: 'cable', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: true, focus: 'Hinge forward and extend the arm straight back with constant cable tension.', alternative: 'Dumbbell Tricep Kickbacks' },
      { name: 'Dumbbell Tricep Kickbacks', equipment: 'dumbbell', movementPattern: 'tricepExtension', primaryMuscle: 'triceps', secondaryMuscles: [], unilateral: true, focus: 'Keep the upper arm parallel to the floor and extend to a hard lockout squeeze.', alternative: 'Cable Kickbacks' }
    ]
  },
  quads: {
    compound: [
      { name: 'Barbell Back Squats', equipment: 'barbell', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes', 'hamstrings'], unilateral: false, focus: 'Depth at or below parallel. Drive through heels. Keep chest up and core tight.', alternative: 'Front Squats' },
      { name: 'Front Squats', equipment: 'barbell', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Bar rests on front delts. More quad emphasis. Keep torso upright.', alternative: 'Goblet Squats' },
      { name: 'Goblet Squats', equipment: 'dumbbell', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Hold dumbbell at chest. Great for learning squat pattern and quad focus.', alternative: 'Barbell Back Squats' },
      { name: 'Leg Press', equipment: 'machine', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes', 'hamstrings'], unilateral: false, focus: 'Place feet shoulder-width apart. Control the negative phase.', alternative: 'Hack Squats' },
      { name: 'Hack Squats', equipment: 'machine', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Machine variation targets quads heavily. Keep back flat against pad.', alternative: 'Leg Press' },
      { name: 'Walking Lunges', equipment: 'dumbbell', movementPattern: 'lunge', primaryMuscle: 'quads', secondaryMuscles: ['glutes', 'hamstrings'], unilateral: true, focus: 'Step forward, knee tracking over toes. Drive through front heel.', alternative: 'Reverse Lunges' },
      { name: 'Bulgarian Split Squats', equipment: 'dumbbell', movementPattern: 'lunge', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: true, focus: 'Rear foot elevated. Great unilateral quad and glute development.', alternative: 'Walking Lunges' },
      { name: 'Smith Machine Squats', equipment: 'machine', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Place feet slightly forward on the fixed bar to bias the quads. Control the depth.', alternative: 'Hack Squats' },
      { name: 'Reverse Lunges', equipment: 'dumbbell', movementPattern: 'lunge', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: true, focus: 'Step back and sink straight down; easier on the knees than forward lunges.', alternative: 'Walking Lunges' },
      { name: 'Barbell Lunges', equipment: 'barbell', movementPattern: 'lunge', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: true, focus: 'Bar on the back, step out and lunge with an upright torso. Drive through the front heel.', alternative: 'Walking Lunges' },
      { name: 'Step-ups', equipment: 'dumbbell', movementPattern: 'lunge', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: true, focus: 'Drive through the top foot onto a knee-height box without pushing off the bottom leg.', alternative: 'Bulgarian Split Squats' },
      { name: 'Leg Press (Narrow Stance)', equipment: 'machine', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: [], unilateral: false, focus: 'Feet low and close together to maximize quad sweep. Keep knees tracking over the toes.', alternative: 'Leg Press' },
      { name: 'Pause Back Squats', equipment: 'barbell', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Hold a 2-3 second pause in the hole to kill the stretch reflex and build control.', alternative: 'Barbell Back Squats' },
      { name: 'Box Squats', equipment: 'barbell', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes', 'hamstrings'], unilateral: false, focus: 'Sit back to a box at parallel, stay tight, then drive up. Teaches depth and control.', alternative: 'Barbell Back Squats' },
      { name: 'Pendulum Squats', equipment: 'machine', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Arced path keeps constant tension on the quads with a knee-friendly groove.', alternative: 'Hack Squats' },
      { name: 'Belt Squats', equipment: 'machine', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Load hangs from the hips, sparing the spine. Squat deep and drive through mid-foot.', alternative: 'Hack Squats' },
      { name: 'Dumbbell Squats', equipment: 'dumbbell', movementPattern: 'squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Hold dumbbells at the sides and squat to depth with an upright chest.', alternative: 'Goblet Squats' },
      { name: 'Smith Machine Lunges', equipment: 'machine', movementPattern: 'lunge', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], unilateral: true, focus: 'Fixed bar path lets you focus purely on driving through the front leg.', alternative: 'Bulgarian Split Squats' }
    ],
    isolation: [
      { name: 'Leg Extensions', equipment: 'machine', movementPattern: 'quadIsolation', primaryMuscle: 'quads', secondaryMuscles: [], unilateral: false, focus: 'Squeeze quads hard at the top. Control the descent. Great for pump.', alternative: 'Sissy Squats' },
      { name: 'Sissy Squats', equipment: 'bodyweight', movementPattern: 'quadIsolation', primaryMuscle: 'quads', secondaryMuscles: [], unilateral: false, focus: 'Lean back on the knees and lower under control for a deep quad stretch. Hold support.', alternative: 'Leg Extensions' },
      { name: 'Single-Leg Extensions', equipment: 'machine', movementPattern: 'quadIsolation', primaryMuscle: 'quads', secondaryMuscles: [], unilateral: true, focus: 'One leg at a time to fix imbalances. Pause and squeeze at full extension.', alternative: 'Leg Extensions' },
      { name: 'Spanish Squats', equipment: 'bodyweight', movementPattern: 'quadIsolation', primaryMuscle: 'quads', secondaryMuscles: [], unilateral: false, focus: 'A band behind the knees lets you sit straight down with constant quad tension.', alternative: 'Sissy Squats' },
      { name: 'Reverse Nordic Curls', equipment: 'bodyweight', movementPattern: 'quadIsolation', primaryMuscle: 'quads', secondaryMuscles: [], unilateral: false, focus: 'Kneel and lean back from the knees, resisting with the quads through a big stretch.', alternative: 'Sissy Squats' },
      { name: 'Banded Leg Extensions', equipment: 'cable', movementPattern: 'quadIsolation', primaryMuscle: 'quads', secondaryMuscles: [], unilateral: false, focus: 'Resistance peaks at lockout. A joint-friendly quad finisher when no machine is free.', alternative: 'Leg Extensions' },
      { name: 'Goblet Cyclist Squat', equipment: 'dumbbell', movementPattern: 'quadIsolation', primaryMuscle: 'quads', secondaryMuscles: [], unilateral: false, focus: 'Heels elevated and torso tall to isolate the quads through a deep range.', alternative: 'Sissy Squats' },
      { name: 'Wall Sit', equipment: 'bodyweight', movementPattern: 'quadIsolation', primaryMuscle: 'quads', secondaryMuscles: [], unilateral: false, focus: 'Hold a 90-degree seated position against a wall for time. A simple quad-burn finisher.', alternative: 'Spanish Squats' }
    ]
  },
  hamstrings: {
    compound: [
      { name: 'Romanian Deadlifts (RDLs)', equipment: 'barbell', movementPattern: 'hipHinge', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Hinge at hips, slight knee bend. Feel the stretch in hamstrings.', alternative: 'Dumbbell RDLs' },
      { name: 'Good Mornings', equipment: 'barbell', movementPattern: 'hipHinge', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Bar on upper back, hinge forward. Feel hamstring stretch. Keep back flat.', alternative: 'Romanian Deadlifts (RDLs)' },
      { name: 'Dumbbell RDLs', equipment: 'dumbbell', movementPattern: 'hipHinge', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Same as barbell but allows more freedom. Great for unilateral variations.', alternative: 'Romanian Deadlifts (RDLs)' },
      { name: 'Stiff-Leg Deadlifts', equipment: 'barbell', movementPattern: 'hipHinge', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Minimal knee bend for maximum hamstring stretch. Keep the bar close to the legs.', alternative: 'Romanian Deadlifts (RDLs)' },
      { name: 'Single-Leg RDLs', equipment: 'dumbbell', movementPattern: 'hipHinge', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes'], unilateral: true, focus: 'Hinge over one leg with a tall spine to load the hamstring and challenge balance.', alternative: 'Dumbbell RDLs' },
      { name: 'Conventional Deadlifts', equipment: 'barbell', movementPattern: 'hipHinge', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes', 'upper-back'], unilateral: false, focus: 'Drive the floor away with a flat back and tight lats. Lock out by squeezing the glutes.', alternative: 'Romanian Deadlifts (RDLs)' },
      { name: 'Sumo Deadlifts', equipment: 'barbell', movementPattern: 'hipHinge', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes', 'quads'], unilateral: false, focus: 'Wide stance, hips closer to the bar. Push the knees out and drive through the floor.', alternative: 'Conventional Deadlifts' },
      { name: 'Trap Bar Deadlifts', equipment: 'barbell', movementPattern: 'hipHinge', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes', 'quads'], unilateral: false, focus: 'Neutral handles keep the load close and the spine safer. Drive up tall and controlled.', alternative: 'Conventional Deadlifts' },
      { name: 'Cable Pull-Throughs', equipment: 'cable', movementPattern: 'hipHinge', primaryMuscle: 'glutes', secondaryMuscles: ['hamstrings'], unilateral: false, focus: 'Hinge and drive the hips through against the cable. Squeeze the glutes hard at lockout.', alternative: 'Good Mornings' },
      { name: 'Kettlebell Swings', equipment: 'dumbbell', movementPattern: 'hipHinge', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Explosive hip hinge that snaps the bell to chest height. Power comes from the hips, not arms.', alternative: 'Cable Pull-Throughs' },
      { name: 'Glute-Ham Raise', equipment: 'bodyweight', movementPattern: 'hipHinge', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Lower under control on the GHD and pull yourself back with the hamstrings.', alternative: 'Nordic Hamstring Curls' },
      { name: 'Nordic Hamstring Curls', equipment: 'bodyweight', movementPattern: 'hamstringCurl', primaryMuscle: 'hamstrings', secondaryMuscles: [], unilateral: false, focus: 'Anchor the ankles and lower the torso as slowly as possible, resisting with the hamstrings.', alternative: 'Glute-Ham Raise' }
    ],
    isolation: [
      { name: 'Lying Leg Curls', equipment: 'machine', movementPattern: 'hamstringCurl', primaryMuscle: 'hamstrings', secondaryMuscles: [], unilateral: false, focus: 'Isolate hamstrings. Focus on full range and controlled movement.', alternative: 'Seated Leg Curls' },
      { name: 'Seated Leg Curls', equipment: 'machine', movementPattern: 'hamstringCurl', primaryMuscle: 'hamstrings', secondaryMuscles: [], unilateral: false, focus: 'More stretch at the start position. Control throughout movement.', alternative: 'Lying Leg Curls' },
      { name: 'Standing Leg Curls', equipment: 'machine', movementPattern: 'hamstringCurl', primaryMuscle: 'hamstrings', secondaryMuscles: [], unilateral: true, focus: 'Curl one leg at a time against the pad. Keep the hips still and squeeze at the top.', alternative: 'Lying Leg Curls' },
      { name: 'Single-Leg Lying Curls', equipment: 'machine', movementPattern: 'hamstringCurl', primaryMuscle: 'hamstrings', secondaryMuscles: [], unilateral: true, focus: 'One leg at a time on the lying machine to even out imbalances.', alternative: 'Lying Leg Curls' },
      { name: 'Dumbbell Leg Curls', equipment: 'dumbbell', movementPattern: 'hamstringCurl', primaryMuscle: 'hamstrings', secondaryMuscles: [], unilateral: false, focus: 'Lie prone and curl a dumbbell gripped between the feet. Slow and controlled.', alternative: 'Lying Leg Curls' },
      { name: 'Swiss Ball Leg Curls', equipment: 'bodyweight', movementPattern: 'hamstringCurl', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes'], unilateral: false, focus: 'Bridge the hips and curl the ball toward you with the heels. Keep the hips elevated.', alternative: 'Lying Leg Curls' },
      { name: 'Slider Leg Curls', equipment: 'bodyweight', movementPattern: 'hamstringCurl', primaryMuscle: 'hamstrings', secondaryMuscles: [], unilateral: false, focus: 'On sliders or a towel, bridge up and pull the heels in, resisting the slide out.', alternative: 'Swiss Ball Leg Curls' },
      { name: 'Cable Leg Curls', equipment: 'cable', movementPattern: 'hamstringCurl', primaryMuscle: 'hamstrings', secondaryMuscles: [], unilateral: false, focus: 'Ankle strap on a low pulley; curl the heel toward the glute with constant tension.', alternative: 'Lying Leg Curls' }
    ]
  },
  calves: {
    exercises: [
      { name: 'Standing Calf Raises', equipment: 'machine', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: false, focus: 'Full stretch at bottom, strong contraction at top. Vary foot position.', alternative: 'Leg Press Calf Raises' },
      { name: 'Seated Calf Raises', equipment: 'machine', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: false, focus: 'Targets soleus muscle. Go through full range of motion.', alternative: 'Standing Calf Raises' },
      { name: 'Leg Press Calf Raises', equipment: 'machine', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: false, focus: 'Use leg press machine for calf raises. Great for heavy loading.', alternative: 'Standing Calf Raises' },
      { name: 'Dumbbell Standing Calf Raises', equipment: 'dumbbell', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: false, focus: 'Hold dumbbells and raise on a step for extra stretch at the bottom.', alternative: 'Standing Calf Raises' },
      { name: 'Single-Leg Calf Raises', equipment: 'dumbbell', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: true, focus: 'One leg at a time with a dumbbell for full loading and balance. Pause at the top.', alternative: 'Dumbbell Standing Calf Raises' },
      { name: 'Smith Machine Calf Raises', equipment: 'machine', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: false, focus: 'Bar on the shoulders over a block for a stable, heavy standing calf raise.', alternative: 'Standing Calf Raises' },
      { name: 'Barbell Calf Raises', equipment: 'barbell', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: false, focus: 'Barbell on the back, raise onto the toes from a deep stretch. Control the descent.', alternative: 'Standing Calf Raises' },
      { name: 'Donkey Calf Raises', equipment: 'machine', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: false, focus: 'Hinged at the hips for a deep gastrocnemius stretch under load.', alternative: 'Standing Calf Raises' },
      { name: 'Seated Dumbbell Calf Raises', equipment: 'dumbbell', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: false, focus: 'Dumbbells on the knees, raise the heels to bias the soleus. Full range each rep.', alternative: 'Seated Calf Raises' },
      { name: 'Calf Press (Leg Press)', equipment: 'machine', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: false, focus: 'Push the sled with the balls of the feet; pause in the stretch and at full plantarflexion.', alternative: 'Leg Press Calf Raises' },
      { name: 'Bodyweight Calf Raises', equipment: 'bodyweight', movementPattern: 'calfRaise', primaryMuscle: 'calves', secondaryMuscles: [], unilateral: false, focus: 'High-rep raises on a step for a deep stretch and burn when no machine is available.', alternative: 'Single-Leg Calf Raises' }
    ]
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ExerciseDatabase };
}
